### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by Speak2Erase** [Speak2Erase/fmod-oxide#3]
- [ ] Fix documentation issues
- [ ] Add support for FMOD 2.0.3
- [ ] More platform support (MacOS, ARM)
- [ ] Better userdata, allow setting userdata to a u64/u32
- [ ] Write tests
- [ ] Better DSP system

**Comment by caspark** [comment]
I investigated 5 Rust FMOD wrapper crates, and this one is my favourite: it works on Linux and Windows (haven't tried MacOS), supports Studio, uses bindgen as I'd expect. And, it has a Rust-y API that hews closely to the C API but is still mostly safe, while still accepting that system creation & shutdown is rare enough that it's not really worth trying to make it safe!

I [integrated](https://www.slowrush.dev/news/fmod-integration/) it into my game last week and it's working well. So, firstly, thank you for making it!

Secondly, are you still using it in tandem with your game as you wrote in the readme, and hence expect to cut new releases for crates.io as they make sense? (Or have you moved on to other things? No judgement if so)

**Comment by melody-rs** [comment]
Thank you!! 💟 

It's kinda complicated. I had 2 projects that were using this crate- [wormhole](https://github.com/Astrabit-ST/wormhole) and [libfmod](https://github.com/Astrabit-ST/libfmod).
I ended up canning wormhole a while ago, and I'm not *actively* using libfmod. 
It's meant to replace all the audio code for [another project](https://store.steampowered.com/app/1569440/OneShot_Fading_Memory/), and for various reasons that hasn't come to fruition yet. libfmod is kinda a mess right now, there's lots of weird deadlocks and I'm pretty sure I'm doing an undefined behavior somewhere because the Ruby GC keeps segfaulting. Instead of focusing on rewriting out all the audio code, I've been focusing on finishing a massive content update we've been working on for a few years. That effort ended up turning into the exact thing I was trying to avoid, and I ended up [rewriting](https://github.com/Astrabit-ST/osfm-mkxp-z) a large part of the codebase. [Twice](https://github.com/melody-rs/sapphire).
I am starting to work on a bevy game with some friends, if that goes anywhere we'd 100% be using this crate!!

Despite all that I do want to keep this project up to date and publish new releases to crates.io!
